# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6252a15abd63341a659073204589987a4e145e4a827b659a7ee7a4e92d0dc7bf3fbf56bdf68f55d8a4ee22a33ac70ccc18f3ea7541a2fd0d06a3d0da9943badc
  aws_access_key_id: AKIAILDCUUMJEOSWHE6Q
  aws_secret_access_key_id: A23JSzTHBxndU20Qg04Lw9LpF6Ra5i9ajb68Zi8B
  aws_region_id: ap-northeast-1
  aws_bucket_name_id: copy-retty
  aws_bucket_url_id: https://s3-ap-northeast-1.amazonaws.com/copy-retty

test:
  secret_key_base: ae6a616a37cc8cd160c871941ad8891fb30bc3ccc6b9fe5cf26fb9862863d88da3764be41ce4412a8c370e5e9735919029228f337230f6218a322d36d62edc26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: 6252a15abd63341a659073204589987a4e145e4a827b659a7ee7a4e92d0dc7bf3fbf56bdf68f55d8a4ee22a33ac70ccc18f3ea7541a2fd0d06a3d0da9943badc
  aws_access_key_id: AKIAILDCUUMJEOSWHE6Q
  aws_secret_access_key_id: A23JSzTHBxndU20Qg04Lw9LpF6Ra5i9ajb68Zi8B
  aws_region_id: ap-northeast-1
  aws_bucket_name_id: copy-retty
  aws_bucket_url_id: https://s3-ap-northeast-1.amazonaws.com/copy-retty